/**
 * Blueprint layout — a paper manifest → the `blueprint/src/` directory that
 * leanblueprint (and `docgen-action` with `blueprint: true`) builds from.
 *
 * ## Why this exists (bean `a1ku`, #1492)
 *
 * The folio `blueprint.yml` runs `docgen-action` with `blueprint: true`, which
 * runs `leanblueprint web` / `pdf` in `<paper>/lean/blueprint/src/`. Nothing
 * wrote that directory: `blueprint-export.ts` produces the CONTENT only, and
 * the one `blueprint/src` in the tree was a hand-written copy — the
 * hand-synced `\lean` / `\uses` the export exists to replace.
 *
 * ## What it writes
 *
 * The layout `leanblueprint new` scaffolds (its own templates, 0.0.20), with
 * every folio-specific part DERIVED:
 *
 * | file | from |
 * |---|---|
 * | `content.tex` | the rendered chapters, in manifest order, through `exportBlueprint` (generated `\lean`, `\leanok`, formal `\uses`), then with the platform's margin annotations stripped |
 * | `macros/common.tex` | one `\newtheorem` per environment the renderer emits (`ENV_NAMES`), and the paper's `macros` |
 * | `macros/web.tex`, `macros/print.tex` | leanblueprint's own: web-only commands as no-ops for the PDF |
 * | `web.tex`, `print.tex`, `plastex.cfg`, `latexmkrc`, `extra_styles.css` | leanblueprint's templates, with the manifest's title and authors |
 *
 * Every file carries a GENERATED header, and the whole directory is written
 * in CI rather than committed: a committed copy is a second answer, free to
 * go stale against the manifest it was made from.
 *
 * ## Why the annotations are stripped, not stubbed
 *
 * `\blockannot[status]{label}{decl}{path}` is what `exportBlueprint` reads
 * each statement's Lean status from, so it must be present on the way IN.
 * On the way out it is margin furniture for the paper PDF; stripping it with
 * the platform's own `stripAnnotations` means neither plasTeX nor xelatex
 * needs to know it exists.
 *
 * Usage:
 *   bun run folio-assistant-sci/content/pipeline/blueprint-layout.ts \
 *     --paper <folio>/<paper>/<paper>.ts [--out <folio>/<paper>/lean/blueprint/src]
 *
 * @module folio-assistant-sci/content/pipeline/blueprint-layout
 */

import { mkdirSync, writeFileSync } from "fs";
import { dirname, join, resolve } from "path";
import type { Paper } from "../../../cat-harness/schemas/types";
import { buildContentGraph } from "../../../cat-harness-tools/content/pipeline/content-graph";
import { stripAnnotations } from "../../../cat-harness-tools/content/pipeline/generate-block-tex";
import { ENV_NAMES } from "../../../cat-harness-tools/content/pipeline/render-latex";
import { findContentRepoRoot } from "../../../cat-harness-tools/content/pipeline/repo-root";
import { folioDir } from "../../../cat-harness/schemas/cat-harness.js";
import { describeExport, exportBlueprint, formalView, type ExportResult, type FormalView } from "./blueprint-export";

export interface LayoutInput {
  paper: Pick<Paper, "title" | "authors" | "macros">;
  /** Rendered chapter TeX, in manifest order. */
  chapters: string[];
  formal: FormalView;
}

export interface LayoutResult {
  /** Path under `blueprint/src/` → file text. */
  files: Record<string, string>;
  export: ExportResult;
}

const HEADER = "% GENERATED by folio-assistant-sci/content/pipeline/blueprint-layout.ts — do not edit; edit the paper manifest or its blocks.\n";

/** The same escaping `generate-main-tex` gives title and author. */
function meta(text: string): string {
  const esc: Record<string, string> = { "\\": "\\textbackslash{}", "&": "\\&", "#": "\\#", "%": "\\%", "_": "\\_" };
  return text.replace(/[\\&#%_]/g, (c) => esc[c] ?? c);
}

/** Highest `#n` in a macro body: its argument count. */
export function macroArity(tex: string): number {
  let n = 0;
  for (const m of tex.matchAll(/#([1-9])/g)) n = Math.max(n, Number(m[1]));
  return n;
}

const PLAIN_STYLE = new Set(["lemma", "proposition", "corollary", "conjecture", "algorithmblock"]);

/**
 * One `\newtheorem` per theorem-like environment the renderer can emit.
 * `proof` is amsthm's own. Numbered on one shared counter, as leanblueprint's
 * template does, so the dependency graph's numbers match the text's.
 */
export function theoremDeclarations(envs: Record<string, string> = ENV_NAMES): string[] {
  const names = [...new Set(Object.values(envs))].filter((e) => e !== "proof" && e !== "theorem");
  const title = (e: string) => (e === "algorithmblock" ? "Algorithm" : e[0]!.toUpperCase() + e.slice(1));
  const decl = (e: string) => `\\newtheorem{${e}}[theorem]{${title(e)}}`;
  // `theorem` is declared first, always: every other environment shares its
  // counter. Claims are upright-italic `plain`; the rest `definition` style.
  return [
    "\\newtheorem{theorem}{Theorem}",
    ...names.filter((e) => PLAIN_STYLE.has(e)).map(decl),
    "\\theoremstyle{definition}",
    ...names.filter((e) => !PLAIN_STYLE.has(e)).map(decl),
  ];
}

const PACKAGES = "\\usepackage{amssymb, amsthm, amsmath}\n\\usepackage{mathrsfs, tikz-cd, booktabs, longtable, array, adjustbox}\n";

export function buildBlueprintLayout(input: LayoutInput): LayoutResult {
  const exported = exportBlueprint(input.chapters.join("\n\n"), input.formal);
  const content = stripAnnotations(exported.tex);
  const title = meta(input.paper.title);
  const authors = (input.paper.authors ?? []).map(meta);
  // `\and` for the PDF; plasTeX's report class has no `\and`, so commas on the web.
  const author = authors.join(" \\and ");
  const webAuthor = authors.join(", ");

  const macros = Object.entries(input.paper.macros ?? {}).map(([name, m]) => {
    const n = macroArity(m.tex);
    return `\\newcommand{\\${name}}${n ? `[${n}]` : ""}{${m.tex}}`;
  });

  const files: Record<string, string> = {
    "content.tex": HEADER + content + "\n",
    "macros/common.tex": [HEADER.trimEnd(), ...theoremDeclarations(), "", ...macros, ""].join("\n"),
    "macros/web.tex": `${HEADER}% Web-only commands. Each has a no-op twin in macros/print.tex.\n`,
    "macros/print.tex": [
      HEADER.trimEnd(),
      "% Commands plasTeX provides for the web version, as no-ops for the PDF (leanblueprint's template).",
      "\\newcommand{\\lean}[1]{}",
      "\\newcommand{\\discussion}[1]{}",
      "\\newcommand{\\leanok}{}",
      "\\newcommand{\\mathlibok}{}",
      "\\newcommand{\\notready}{}",
      "\\ExplSyntaxOn",
      "\\NewDocumentCommand{\\uses}{m}",
      " {\\clist_map_inline:nn{#1}{\\vphantom{\\ref{##1}}}%",
      "  \\ignorespaces}",
      "\\NewDocumentCommand{\\proves}{m}",
      " {\\clist_map_inline:nn{#1}{\\vphantom{\\ref{##1}}}%",
      "  \\ignorespaces}",
      "\\ExplSyntaxOff",
      "",
    ].join("\n"),
    "web.tex": [
      HEADER.trimEnd(),
      "\\documentclass{report}",
      PACKAGES.trimEnd(),
      "\\usepackage{hyperref}",
      "\\usepackage[showmore, dep_graph]{blueprint}",
      "\\input{macros/common}",
      "\\input{macros/web}",
      `\\title{${title}}`,
      `\\author{${webAuthor}}`,
      "\\begin{document}",
      "\\maketitle",
      "\\input{content}",
      "\\end{document}",
      "",
    ].join("\n"),
    "print.tex": [
      HEADER.trimEnd(),
      "\\documentclass[a4paper]{report}",
      "\\usepackage{geometry}",
      "\\usepackage{expl3}",
      PACKAGES.trimEnd(),
      "\\usepackage[unicode,colorlinks=true,linkcolor=blue,urlcolor=magenta,citecolor=blue]{hyperref}",
      "\\input{macros/common}",
      "\\input{macros/print}",
      `\\title{${title}}`,
      `\\author{${author}}`,
      "\\begin{document}",
      "\\maketitle",
      "\\input{content}",
      "\\end{document}",
      "",
    ].join("\n"),
    "plastex.cfg": [
      "# GENERATED by blueprint-layout.ts — leanblueprint's template.",
      "[general]",
      "renderer=HTML5",
      "copy-theme-extras=yes",
      "plugins=plastexdepgraph plastexshowmore leanblueprint",
      "",
      "[document]",
      "toc-depth=3",
      "toc-non-files=True",
      "",
      "[files]",
      "directory=../web/",
      "split-level=0",
      "",
      "[html5]",
      "localtoc-level=0",
      "extra-css=extra_styles.css",
      "mathjax-dollars=False",
      "",
    ].join("\n"),
    // pdflatex, not leanblueprint's xelatex: the rendered chapters are
    // written for the paper's pdflatex build (T1, no unicode-math).
    latexmkrc: "# GENERATED by blueprint-layout.ts\n$pdf_mode = 1;\n$pdflatex = 'pdflatex -synctex=1';\n@default_files = ('print.tex');\n",
    "extra_styles.css": "/* GENERATED by blueprint-layout.ts */\n",
  };
  return { files, export: exported };
}

// ── CLI ─────────────────────────────────────────────────────────

if (import.meta.main) {
  const args = process.argv.slice(2);
  const opt = (k: string) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : undefined; };
  const paperArg = opt("--paper");
  if (!paperArg) {
    console.error("usage: blueprint-layout.ts --paper <folio>/<paper>/<paper>.ts [--out <dir>]");
    process.exit(2);
  }
  const paperPath = resolve(paperArg);
  const out = resolve(opt("--out") ?? join(dirname(paperPath), "lean", "blueprint", "src"));
  const { buildPaper } = await import("../../../cat-harness-tools/content/pipeline/build");
  const built = await buildPaper(paperPath);
  const paper = (await import(paperPath)).default as Paper;
  const chapters = [...built.chapters.entries()]
    .filter(([n]) => !built.appendixChapters.has(n))
    .sort(([a], [b]) => a - b)
    .map(([, tex]) => tex);
  const repoRoot = findContentRepoRoot();
  const r = buildBlueprintLayout({ paper, chapters, formal: formalView(buildContentGraph(folioDir(repoRoot), repoRoot)) });
  for (const [f, text] of Object.entries(r.files)) {
    mkdirSync(dirname(join(out, f)), { recursive: true });
    writeFileSync(join(out, f), text);
  }
  console.log(describeExport(r.export));
  console.log(`wrote ${Object.keys(r.files).length} files to ${out}`);
}
