@echo off
setlocal
rem Windows entry point for folio-assistant-sci/adapters/paper/latex/feature-build.sh -- generated by cat-harness/scripts/gen-bat-wrappers.sh; do not hand-edit.
rem Runs the sibling .sh under Git Bash with the same arguments. Git for Windows is required.
set "SCRIPT=%~dpn0.sh"
set "BASH="
for %%B in ("%ProgramFiles%\Git\bin\bash.exe" "%ProgramFiles(x86)%\Git\bin\bash.exe" "%LocalAppData%\Programs\Git\bin\bash.exe") do if not defined BASH if exist %%B set "BASH=%%~B"
if not defined BASH for /f "delims=" %%G in ('where git.exe 2^>nul') do if not defined BASH if exist "%%~dpG..\bin\bash.exe" set "BASH=%%~dpG..\bin\bash.exe"
if not defined BASH (
  echo [%~nx0] Git Bash not found. Install Git for Windows from https://git-scm.com/download/win 1>&2
  exit /b 2
)
if not exist "%SCRIPT%" (
  echo [%~nx0] missing sibling script: %SCRIPT% 1>&2
  exit /b 2
)
"%BASH%" "%SCRIPT%" %*
exit /b %ERRORLEVEL%
